FROM node:22.14.0-alpine

RUN apk add --no-cache \
    build-base \
    g++ \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    giflib-dev

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run prisma:generate

EXPOSE 3333

CMD [ "npm", "run", "prisma:seed" ]